include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  exclude: [build/**, lib/**/*.g.dart]
  errors:
    todo: ignore
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
